version: "3"
services:
  password-generator:
    build:
      context: ./
    image: "raphacm/password-generator:latest"
    container_name: password_generator_react
    ports:
      - "3000:8080"
    env_file:
      - ./.env.dist
